### ISSUE TITLE
Can asari distinguish the number of charges?

### ISSUE THREAD

**Issue by xieyying** [shuzhao-li/asari#40]
Hi, shuzhao, I used asari for extracting features for compounds with double charges. But I found the resulting features can not give the correct charge number. Can asari distinguish the number of charges?

**Comment by xieyying** [comment]
Thanks for your prompt response. I tried doing annotation using Khipu and asari output, but the double-charged forms were still not identified. The data was acquired using waters Xevo G2-XS QTof. Then I tried to use higher errors of 10, 20, and 30 ppm, however, the double-charged forms were still not recognized. 




Except for the double-charge forms, [2M+H]+, [2M+Na]+ are usually found in mass spectra and can be added as adducts in the khipu. 




For convenience, I attached the asari output file the full-Feature_table.tsv and the manually curated annotations.




--







At 2023-05-03 21:12:51, "Shuzhao" ***@***.***> wrote:

You are right that the default isotope/adduct search only includes two double charged forms, as in default_parameters.py.
We can add more quickly. Please feel free to suggest your favorite adducts too.

The preannotation is using khipu (asari focuses on feature extraction). One can also use khipu to redo annotation from asari output.

**Comment by shuzhao-li** [comment]
What I meant is like this example:
https://github.com/shuzhao-li-lab/khipu/blob/main/notebooks/custom_adduct_isotope_patterns.ipynb

khipu does not search for the adducts because it is not told to.
Thanks for the suggestions. We will extend the default list on the next version.
GitHub issues do not show emails. It'd be nice to identify yourself, BTW.

**Comment by shuzhao-li** [comment]
We'll add them to khipu package in the next week or two.

**Comment by xieyying** [comment]
Thanks. Asari is a wonderful tool for mass preprocessing. BTW.



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/08/2023 21:47 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [shuzhao-li/asari] Can asari distinguish the number of charges? (Issue #40) |

We'll add them to khipu package in the next week or two.

**Comment by shuzhao-li** [comment]
Added annotation of multiple charged ions via JMS 0.5.7, khipu 0.7.0.
Upgrade to version 1.11.4:
`pip3 install --upgrade asari-metabolomics`

This update only annotates multiple charged ions in empirical compounds with more than one ions. 
When an ion has no relationship to others, we assume it's single charged, just because we don't know.
